services:
  postgres:
    image: postgres:15
    container_name: report_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5470:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    container_name: report_migrate
    restart: on-failure
    depends_on:
      - postgres
    volumes:
      - ./backend/migrations:/migrations
    command: [
      "-path=/migrations",
      "-database=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable",
      "up"
    ]

  backend:
    build: ./backend
    container_name: report_backend
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}

      SERVER_PORT: ${SERVER_PORT}
      JWT_SECRET: ${JWT_SECRET}

      UPLOAD_DIR: ${UPLOAD_DIR}
      BASE_URL: ${BASE_URL}

      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      CORS_ALLOW_CREDENTIALS: ${CORS_ALLOW_CREDENTIALS}
    ports:
      - "8090:8080"

  frontend:
    build: ./frontend
    container_name: report_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3010:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  pgdata: